package com.everis.springbootjpaactividades.model;
// Generated 18/09/2019 12:35:21 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "actividadesdb")
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private String nombre;
	private String password;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, String nombre, String password) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.password = password;
	}

	public Usuario(int idUsuario, String nombre, String password, Set<Empleado> empleados) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.password = password;
		this.empleados = empleados;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
