version: '3'
services:
  web:
    image: nginx
    ports:
    - "9898:80"
    depends_on:
    - db
  db:
    image: mysql
    ports:
    - "3308:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=academiadb