package com.everis.springbootjparelaciones.model;
// Generated 17/09/2019 04:38:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compraproducto generated by hbm2java
 */
@Entity
@Table(name = "compraproducto", catalog = "cintegracion")
public class Compraproducto implements java.io.Serializable {

	private Integer idcompraproducto;
	private Compra compra;
	private Producto producto;
	private int cantidad;
	private BigDecimal preciounitario;

	public Compraproducto() {
	}

	public Compraproducto(Compra compra, Producto producto, int cantidad, BigDecimal preciounitario) {
		this.compra = compra;
		this.producto = producto;
		this.cantidad = cantidad;
		this.preciounitario = preciounitario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompraproducto", unique = true, nullable = false)
	public Integer getIdcompraproducto() {
		return this.idcompraproducto;
	}

	public void setIdcompraproducto(Integer idcompraproducto) {
		this.idcompraproducto = idcompraproducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcompra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "preciounitario", nullable = false, precision = 7)
	public BigDecimal getPreciounitario() {
		return this.preciounitario;
	}

	public void setPreciounitario(BigDecimal preciounitario) {
		this.preciounitario = preciounitario;
	}

}
