package com.everis.springbootjparelaciones.model;
// Generated 17/09/2019 04:38:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "cintegracion")
public class Compra implements java.io.Serializable {

	private Integer idcompra;
	private Cliente cliente;
	private Date fechacompra;
	private BigDecimal total;
	private Set<Compraproducto> compraproductos = new HashSet<Compraproducto>(0);

	public Compra() {
	}

	public Compra(Cliente cliente, Date fechacompra, BigDecimal total) {
		this.cliente = cliente;
		this.fechacompra = fechacompra;
		this.total = total;
	}

	public Compra(Cliente cliente, Date fechacompra, BigDecimal total, Set<Compraproducto> compraproductos) {
		this.cliente = cliente;
		this.fechacompra = fechacompra;
		this.total = total;
		this.compraproductos = compraproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompra", unique = true, nullable = false)
	public Integer getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(Integer idcompra) {
		this.idcompra = idcompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacompra", nullable = false, length = 10)
	public Date getFechacompra() {
		return this.fechacompra;
	}

	public void setFechacompra(Date fechacompra) {
		this.fechacompra = fechacompra;
	}

	@Column(name = "total", nullable = false, precision = 7)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compra")
	public Set<Compraproducto> getCompraproductos() {
		return this.compraproductos;
	}

	public void setCompraproductos(Set<Compraproducto> compraproductos) {
		this.compraproductos = compraproductos;
	}

}
