package com.everis.springbootjparelaciones.model;
// Generated 17/09/2019 04:38:12 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "cintegracion")
public class Producto implements java.io.Serializable {

	private Integer idproducto;
	private Categoria categoria;
	private String nombre;
	private Date fecharegistro;
	private BigDecimal precio;
	private String imagen;
	private int stock;
	//private Set<Compraproducto> compraproductos = new HashSet<Compraproducto>(0);

	public Producto() {
	}

	public Producto(Categoria categoria, String nombre, Date fecharegistro, BigDecimal precio, String imagen,
			int stock) {
		this.categoria = categoria;
		this.nombre = nombre;
		this.fecharegistro = fecharegistro;
		this.precio = precio;
		this.imagen = imagen;
		this.stock = stock;
	}

//	public Producto(Categoria categoria, String nombre, Date fecharegistro, BigDecimal precio, String imagen, int stock,
//			Set<Compraproducto> compraproductos) {
//		this.categoria = categoria;
//		this.nombre = nombre;
//		this.fecharegistro = fecharegistro;
//		this.precio = precio;
//		this.imagen = imagen;
//		this.stock = stock;
//		this.compraproductos = compraproductos;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idproducto", unique = true, nullable = false)
	public Integer getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	//LAZY carga la relacion entre entidades 
	
	@ManyToOne(fetch = FetchType.EAGER) //LAZY
	@JoinColumn(name = "idcategoria", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecharegistro", nullable = false, length = 10)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "precio", nullable = false, precision = 7)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "imagen", nullable = false, length = 200)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
//	public Set<Compraproducto> getCompraproductos() {
//		return this.compraproductos;
//	}
//
//	public void setCompraproductos(Set<Compraproducto> compraproductos) {
//		this.compraproductos = compraproductos;
//	}

}
