package com.everis.springbootactividadesdb.model;
// Generated 20/09/2019 12:54:39 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name = "bitacora", catalog = "actividadesdb")
public class Bitacora implements java.io.Serializable {

	private int idbitacora;
	private Actividadasignada actividadasignada;
	private String estado;
	private Date fecha;

	public Bitacora() {
	}

	public Bitacora(int idbitacora, Actividadasignada actividadasignada, String estado, Date fecha) {
		this.idbitacora = idbitacora;
		this.actividadasignada = actividadasignada;
		this.estado = estado;
		this.fecha = fecha;
	}

	@Id

	@Column(name = "idbitacora", unique = true, nullable = false)
	public int getIdbitacora() {
		return this.idbitacora;
	}

	public void setIdbitacora(int idbitacora) {
		this.idbitacora = idbitacora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idactividadasignada", nullable = false)
	public Actividadasignada getActividadasignada() {
		return this.actividadasignada;
	}

	public void setActividadasignada(Actividadasignada actividadasignada) {
		this.actividadasignada = actividadasignada;
	}

	@Column(name = "estado", nullable = false, length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
