package com.everis.springbootactividadesdb.model;
// Generated 20/09/2019 12:54:39 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", catalog = "actividadesdb")
public class Empleado implements java.io.Serializable {

	private int idempleado;
	private Usuario usuario;
	private String nombre;
	private String apaterno;
	private String amaterno;
	private Set<Actividadasignada> actividadasignadas = new HashSet<Actividadasignada>(0);

	public Empleado() {
	}

	public Empleado(int idempleado, Usuario usuario, String nombre, String apaterno, String amaterno) {
		this.idempleado = idempleado;
		this.usuario = usuario;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
	}

	public Empleado(int idempleado, Usuario usuario, String nombre, String apaterno, String amaterno,
			Set<Actividadasignada> actividadasignadas) {
		this.idempleado = idempleado;
		this.usuario = usuario;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.actividadasignadas = actividadasignadas;
	}

	@Id

	@Column(name = "idempleado", unique = true, nullable = false)
	public int getIdempleado() {
		return this.idempleado;
	}

	public void setIdempleado(int idempleado) {
		this.idempleado = idempleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apaterno", nullable = false, length = 45)
	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	@Column(name = "amaterno", nullable = false, length = 45)
	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<Actividadasignada> getActividadasignadas() {
		return this.actividadasignadas;
	}

	public void setActividadasignadas(Set<Actividadasignada> actividadasignadas) {
		this.actividadasignadas = actividadasignadas;
	}

}
