package com.everis.springbootjpa.model;
//Generated 17/09/2019 03:12:39 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Categoria generated by hbm2java
*/
@Entity
@Table(name = "cliente", catalog = "cintegracion")
public class Cliente {
	private Integer id;
	private String nombre;
	private String apaterno;
	private String amaterno;
	private String rfc;

	public Cliente() {
		
   }
	
	public Cliente(String nobre) {
		this.nombre = nombre;
	}
	public Cliente(String nombre, String apaterno, String amaterno, String rfc) {
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.rfc =  rfc;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apaterno", length = 200)
	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;

	}
	
	@Column(name = "amaterno", nullable = false, length = 50)
	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	@Column(name = "rfc", length = 50)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;

	}
	
}

	