package com.everis.springbootjpaactividades.model;
// Generated 18/09/2019 12:41:08 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actividadasignada generated by hbm2java
 */
@Entity
@Table(name = "actividadasignada", catalog = "actividadesdb")
public class Actividadasignada implements java.io.Serializable {

	private int idactividadasignada;
	private Actividad actividad;
	private Empleado empleado;
	private Date fechainicio;
	private Date fechafin;
	private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

	public Actividadasignada() {
	}

	public Actividadasignada(int idactividadasignada, Actividad actividad, Empleado empleado, Date fechainicio,
			Date fechafin) {
		this.idactividadasignada = idactividadasignada;
		this.actividad = actividad;
		this.empleado = empleado;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	public Actividadasignada(int idactividadasignada, Actividad actividad, Empleado empleado, Date fechainicio,
			Date fechafin, Set<Bitacora> bitacoras) {
		this.idactividadasignada = idactividadasignada;
		this.actividad = actividad;
		this.empleado = empleado;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.bitacoras = bitacoras;
	}

	@Id

	@Column(name = "idactividadasignada", unique = true, nullable = false)
	public int getIdactividadasignada() {
		return this.idactividadasignada;
	}

	public void setIdactividadasignada(int idactividadasignada) {
		this.idactividadasignada = idactividadasignada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idactividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idempleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", nullable = false, length = 19)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", nullable = false, length = 19)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividadasignada")
	public Set<Bitacora> getBitacoras() {
		return this.bitacoras;
	}

	public void setBitacoras(Set<Bitacora> bitacoras) {
		this.bitacoras = bitacoras;
	}

}
