package com.everis.equipo1frontendsemana2.model;
// Generated 18/09/2019 12:21:43 PM by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;


import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Alumno generated by hbm2java
 */

public class Alumno implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apaterno;
	private String amaterno;

	private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

	public Alumno() {
	}

	public Alumno(String nombre) {
		this.nombre = nombre;
	}

	public Alumno(String nombre, String apaterno, String amaterno, Set<Inscripcion> inscripcions) {
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.inscripcions = inscripcions;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	
	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}


	public Set<Inscripcion> getInscripcions() {
		return this.inscripcions;
	}

	public void setInscripcions(Set<Inscripcion> inscripcions) {
		this.inscripcions = inscripcions;
	}

}
