package com.everis.springbootjprexamen.model;
// Generated 20/09/2019 02:04:20 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "examen2")
public class Product implements java.io.Serializable {

	private Integer idProduct;
	private String nombre;
	private String precio;
	private int descriptionIdDescription;

	public Product() {
	}

	public Product(String nombre, String precio, int descriptionIdDescription) {
		this.nombre = nombre;
		this.precio = precio;
		this.descriptionIdDescription = descriptionIdDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProduct", unique = true, nullable = false)
	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", nullable = false, length = 45)
	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	@Column(name = "Description_idDescription", nullable = false)
	public int getDescriptionIdDescription() {
		return this.descriptionIdDescription;
	}

	public void setDescriptionIdDescription(int descriptionIdDescription) {
		this.descriptionIdDescription = descriptionIdDescription;
	}

}
